version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/django
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/react/public
      - ./frontend/src:/react/src
      - ./frontend/package.json:/react/package.json
    ports:
      - "3000:3000"

volumes:
  postgres_data:
