# Generated by Django 4.0.1 on 2024-05-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('campaigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='campaigns.campaigns')),
            ],
        ),
    ]
